### ISSUE TITLE
REQ: port to VS Code

### ISSUE THREAD

**Issue by fpigeonjr** [vinkla/atom-octocat-syntax#2]
Request port to **Visual Studio Code**.

This is a beautiful theme for **Atom** and I would love to use it for **vscode**.

Thanks for creating this!

**Comment by vinkla** [comment]
Thanks for the suggestion. I think there are similar syntax themes available for VSC already. This package might be deprecated in favour of the [official GitHub syntax theme](https://github.com/primer/github-atom-light-syntax).  If the pull requests https://github.com/primer/github-syntax-theme-generator/pull/53 and https://github.com/primer/github-syntax-theme-generator/pull/52 gets merged I'll most likely abandon this package. 

They are working on a VSC adapter: https://github.com/primer/github-syntax-theme-generator/pull/54
